# Generated by Django 4.0.1 on 2022-01-06 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsub',
            name='subordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
