# Generated by Django 4.0.1 on 2022-01-06 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
